import image from "assets/icons/aml/image.png";

export const BIRTH = [
  { id: 0, title: "Same Year" },
  { id: 1, title: "Exact Match" },
  { id: 2, title: "1 year" },
  { id: 3, title: "3 years" },
  { id: 4, title: "5 years" },
];

export const LOCATIONS = [
  { id: 0, title: "All" },
  { id: 1, title: "Afghanistan" },
  { id: 2, title: "Albania" },
  { id: 3, title: "Algeria" },
  { id: 4, title: "American Samoa" },
  { id: 5, title: "Andorra" },
  { id: 6, title: "Angola" },
  { id: 7, title: "Anguilla" },
  { id: 8, title: "Antarctica" },
  { id: 9, title: "Antigua and Barbuda" },
  { id: 10, title: "Argentina" },
  { id: 11, title: "Armenia" },
  { id: 12, title: "Aruba" },
  { id: 13, title: "Australia" },
  { id: 14, title: "Austria" },
  { id: 15, title: "Azerbaijan" },
  { id: 16, title: "Bahamas" },
  { id: 17, title: "Bahrain" },
  { id: 18, title: "Bangladesh" },
  { id: 19, title: "Barbados" },
  { id: 20, title: "Belarus" },
  { id: 21, title: "Belgium" },
  { id: 22, title: "Belize" },
  { id: 23, title: "Benin" },
  { id: 24, title: "Bermuda" },
  { id: 25, title: "Bhutan" },
  { id: 26, title: "Bolivia" },
  { id: 27, title: "Bosnia and Herzegovina" },
  { id: 28, title: "Botswana" },
  { id: 29, title: "Brazil" },
  { id: 30, title: "British Indian Ocean Territory" },
  { id: 31, title: "British Virgin Islands" },
  { id: 32, title: "Brunei" },
  { id: 33, title: "Bulgaria" },
  { id: 34, title: "Burkina Faso" },
  { id: 35, title: "Burundi" },
  { id: 36, title: "Cambodia" },
  { id: 37, title: "Cameroon" },
  { id: 38, title: "Canada" },
  { id: 39, title: "Cape Verde" },
  { id: 40, title: "Cayman Islands" },
  { id: 41, title: "Central African Republic" },
  { id: 42, title: "Chad" },
  { id: 43, title: "Chile" },
  { id: 44, title: "China" },
  { id: 45, title: "Christmas Island" },
  { id: 46, title: "Cocos Islands" },
  { id: 47, title: "Colombia" },
  { id: 48, title: "Comoros" },
  { id: 49, title: "Cook Islands" },
  { id: 50, title: "Costa Rica" },
  { id: 51, title: "Croatia" },
  { id: 52, title: "Cuba" },
  { id: 53, title: "Curacao" },
  { id: 54, title: "Cyprus" },
  { id: 55, title: "Czech Republic" },
  { id: 56, title: "Democratic Republic of the Congo" },
  { id: 57, title: "Denmark" },
  { id: 58, title: "Djibouti" },
  { id: 59, title: "Dominica" },
  { id: 60, title: "Dominican Republic" },
  { id: 61, title: "East Timor" },
  { id: 62, title: "Ecuador" },
  { id: 63, title: "Egypt" },
  { id: 64, title: "El Salvador" },
  { id: 65, title: "Equatorial Guinea" },
  { id: 66, title: "Eritrea" },
  { id: 67, title: "Estonia" },
  { id: 68, title: "Ethiopia" },
  { id: 69, title: "Falkland Islands" },
  { id: 70, title: "Faroe Islands" },
  { id: 71, title: "Fiji" },
  { id: 72, title: "Finland" },
  { id: 73, title: "France" },
  { id: 74, title: "French Polynesia" },
  { id: 75, title: "Gabon" },
  { id: 76, title: "Gambia" },
  { id: 77, title: "Georgia" },
  { id: 78, title: "Germany" },
  { id: 79, title: "Ghana" },
  { id: 80, title: "Gibraltar" },
  { id: 81, title: "Greece" },
  { id: 82, title: "Greenland" },
  { id: 83, title: "Grenada" },
  { id: 84, title: "Guam" },
  { id: 85, title: "Guatemala" },
  { id: 86, title: "Guernsey" },
  { id: 87, title: "Guinea" },
  { id: 88, title: "Guinea-Bissau" },
  { id: 89, title: "Guyana" },
  { id: 90, title: "Haiti" },
  { id: 91, title: "Honduras" },
  { id: 92, title: "Hong Kong" },
  { id: 93, title: "Hungary" },
  { id: 94, title: "Iceland" },
  { id: 95, title: "India" },
  { id: 96, title: "Indonesia" },
  { id: 97, title: "Iran" },
  { id: 98, title: "Iraq" },
  { id: 99, title: "Ireland" },
  { id: 100, title: "Isle of Man" },
  { id: 101, title: "Israel" },
  { id: 102, title: "Italy" },
  { id: 103, title: "Ivory Coast" },
  { id: 104, title: "Jamaica" },
  { id: 105, title: "Japan" },
  { id: 106, title: "Jersey" },
  { id: 107, title: "Jordan" },
  { id: 108, title: "Kazakhstan" },
  { id: 109, title: "Kenya" },
  { id: 110, title: "Kiribati" },
  { id: 111, title: "Kosovo" },
  { id: 112, title: "Kuwait" },
  { id: 113, title: "Kyrgyzstan" },
  { id: 114, title: "Laos" },
  { id: 115, title: "Latvia" },
  { id: 116, title: "Lebanon" },
  { id: 117, title: "Lesotho" },
  { id: 118, title: "Liberia" },
  { id: 119, title: "Libya" },
  { id: 120, title: "Liechtenstein" },
  { id: 121, title: "Lithuania" },
  { id: 122, title: "Luxembourg" },
  { id: 123, title: "Macau" },
  { id: 124, title: "Macedonia" },
  { id: 125, title: "Madagascar" },
  { id: 126, title: "Malawi" },
  { id: 127, title: "Malaysia" },
  { id: 128, title: "Maldives" },
  { id: 129, title: "Mali" },
  { id: 130, title: "Malta" },
  { id: 131, title: "Marshall Islands" },
  { id: 132, title: "Mauritania" },
  { id: 133, title: "Mauritius" },
  { id: 134, title: "Mayotte" },
  { id: 135, title: "Mexico" },
  { id: 136, title: "Micronesia" },
  { id: 137, title: "Moldova" },
  { id: 138, title: "Monaco" },
  { id: 139, title: "Mongolia" },
  { id: 140, title: "Montenegro" },
  { id: 141, title: "Montserrat" },
  { id: 142, title: "Morocco" },
  { id: 143, title: "Mozambique" },
  { id: 144, title: "Myanmar" },
  { id: 145, title: "Namibia" },
  { id: 146, title: "Nauru" },
  { id: 147, title: "Nepal" },
  { id: 148, title: "Netherlands" },
  { id: 149, title: "Netherlands Antilles" },
  { id: 150, title: "New Caledonia" },
  { id: 151, title: "New Zealand" },
  { id: 152, title: "Nicaragua" },
  { id: 153, title: "Niger" },
  { id: 154, title: "Nigeria" },
  { id: 155, title: "Niue" },
  { id: 156, title: "North Korea" },
  { id: 157, title: "Northern Mariana Islands" },
  { id: 158, title: "Norway" },
  { id: 159, title: "Oman" },
  { id: 160, title: "Pakistan" },
  { id: 161, title: "Palau" },
  { id: 162, title: "Palestine" },
  { id: 163, title: "Panama" },
  { id: 164, title: "Papua New Guinea" },
  { id: 165, title: "Paraguay" },
  { id: 166, title: "Peru" },
  { id: 167, title: "Philippines" },
  { id: 168, title: "Pitcairn" },
  { id: 169, title: "Poland" },
  { id: 170, title: "Portugal" },
  { id: 171, title: "Puerto Rico" },
  { id: 172, title: "Qatar" },
  { id: 173, title: "Republic of the Congo" },
  { id: 174, title: "Reunion" },
  { id: 175, title: "Romania" },
  { id: 176, title: "Russia" },
  { id: 177, title: "Rwanda" },
  { id: 178, title: "Saint Barthelemy" },
  { id: 179, title: "Saint Helena" },
  { id: 180, title: "Saint Kitts and Nevis" },
  { id: 181, title: "Saint Lucia" },
  { id: 182, title: "Saint Martin" },
  { id: 183, title: "Saint Pierre and Miquelon" },
  { id: 184, title: "Saint Vincent and the Grenadines" },
  { id: 185, title: "Samoa" },
  { id: 186, title: "San Marino" },
  { id: 187, title: "Sao Tome and Principe" },
  { id: 188, title: "Saudi Arabia" },
  { id: 189, title: "Senegal" },
  { id: 190, title: "Serbia" },
  { id: 191, title: "Seychelles" },
  { id: 192, title: "Sierra Leone" },
  { id: 193, title: "Singapore" },
  { id: 194, title: "Sint Maarten" },
  { id: 195, title: "Slovakia" },
  { id: 196, title: "Slovenia" },
  { id: 197, title: "Solomon Islands" },
  { id: 198, title: "Somalia" },
  { id: 199, title: "South Africa" },
  { id: 200, title: "South Korea" },
  { id: 201, title: "South Sudan" },
  { id: 202, title: "Spain" },
  { id: 203, title: "Sri Lanka" },
  { id: 204, title: "Sudan" },
  { id: 205, title: "Suriname" },
  { id: 206, title: "Svalbard and Jan Mayen" },
  { id: 207, title: "Swaziland" },
  { id: 208, title: "Sweden" },
  { id: 209, title: "Switzerland" },
  { id: 210, title: "Syria" },
  { id: 211, title: "Taiwan" },
  { id: 212, title: "Tajikistan" },
  { id: 213, title: "Tanzania" },
  { id: 214, title: "Thailand" },
  { id: 215, title: "Togo" },
  { id: 216, title: "Tokelau" },
  { id: 217, title: "Tonga" },
  { id: 218, title: "Trinidad and Tobago" },
  { id: 219, title: "Tunisia" },
  { id: 220, title: "Turkey" },
  { id: 221, title: "Turkmenistan" },
  { id: 222, title: "Turks and Caicos Islands" },
  { id: 223, title: "Tuvalu" },
  { id: 224, title: "U.S. Virgin Islands" },
  { id: 225, title: "Uganda" },
  { id: 226, title: "Ukraine" },
  { id: 227, title: "United Arab Emirates" },
  { id: 228, title: "United Kingdom" },
  { id: 229, title: "United States" },
  { id: 230, title: "Uruguay" },
  { id: 231, title: "Uzbekistan" },
  { id: 232, title: "Vanuatu" },
  { id: 233, title: "Vatican" },
  { id: 234, title: "Venezuela" },
  { id: 235, title: "Vietnam" },
  { id: 236, title: "Wallis and Futuna" },
  { id: 237, title: "Western Sahara" },
  { id: 238, title: "Yemen" },
  { id: 239, title: "Zambia" },
  { id: 240, title: "Zimbabwe" },
];




export const SEARCH_OPTION = [
  { id: 0, title: "Individual Search", content:"individual" },
  { id: 1, title: "Bussiness Search", content:"business" },
];

export const DATASETS = [
  {
    id: 0,
    title: "PEP-CURRENT",
    color: "bg-blue-200",
    text: "text-blue-900",
    content: "PEP-CURRENT",
  },
  {
    id: 1,
    title: "PEP-FORMER",
    color: "bg-blue-200",
    text: "text-blue-900",
    content: "PEP-FORMER",
  },
  {
    id: 2,
    title: "PEP-LINKED",
    color: "bg-blue-200",
    text: "text-blue-900",
    content: "PEP-LINKED",
  },
  {
    id: 3,
    title: "SAN-CURRENT",
    color: "bg-orange-100",
    text: "text-orange-700",
    content: "Sanction Current",
  },
  {
    id: 4,
    title: "SAN-FORMER",
    color: "bg-orange-100",
    text: "text-orange-700",
    content: "Sanction Former",
  },
  {
    id: 5,
    title: "RRE",
    color: "bg-violet-100",
    text: "text-violet-600",
    content: "Reputational Risk Exposure",
  },
  // {
  //   id: 6,
  //   title: "INS",
  //   color: "bg-sky-200",
  //   text: "text-sky-600",
  //   content: "Insolvency (UK & Ireland)",
  // },
  // {
  //   id: 7,
  //   title: "DD",
  //   color: "bg-cyan-200",
  //   text: "text-cyan-600",
  //   content: "Disqualified Director (UK only)",
  // },
  {
    id: 6,
    title: "POI",
    color: "bg-blue-600",
    text: "text-blue-100",
    content: "Profile of Interest",
  },
  {
    id: 7,
    title: "REL",
    color: "bg-pink-100",
    text: "text-pink-800",
    content: "Regulatory Enfocement List",
  },
];

export const VIEWS = [
  { id: 0, title: "View 20 items", content: 20 },
  { id: 1, title: "View 50 items", content: 50 },
  { id: 2, title: "View 100 items", content: 100 },
];

export const SEARCH_TYPE = [
  { id: 0, title: "Name Search" },
  { id: 1, title: "Quick Reference" },
];

export const DATA = {
  id: 0,
  qr: "#11040348",
  image: image,
  name: "Donald John Trump",
  birth: "31/12/1977",
  countries: "Country",
  match: "97%",
  dataSet: ["PEP", "SAN", "PRE", "PEP", "SAN", "PRE", "PEP", "SAN", "PRE"],
};

export const CORE_DATA = [
  { id: 0, title: "Forename", content: "Donald" },
  { id: 1, title: "Middle name", content: "John" },
  { id: 2, title: "Surname", content: "Trump" },
  { id: 3, title: "Gender", content: "Male" },
];

export const ALIASES = [
  { id: 0, content: "Donald Trump" },
  { id: 1, content: "Donald John Trump" },
  { id: 2, content: "Donald J Trump" },
  { id: 3, content: "The Donald" },
];

export const ADDRESS = [
  {
    id: 0,
    content:
      "725 Fifth Avenue, Manhattan, New York City, New York, 10022, Unites States of America (the)",
    subContent: "(Residential)",
  },
  {
    id: 1,
    content:
      "725 Fifth Avenue, Manhattan, New York City, New York, 10022, Unites States of America (the)",
    subContent: "(Residential)",
  },
  {
    id: 2,
    content:
      "725 Fifth Avenue, Manhattan, New York City, New York, 10022, Unites States of America (the)",
    subContent: "(Residential)",
  },
];

export const ASSOCIATIONS_MENUS = [
  { id: 0, title: "Relatives & Close Assciations (44)" },
  { id: 1, title: "Associated Businesses (31)" },
];

export const ASSOCIATIONS = {
  title: "Carla Bruni (#12209536)",
  subTitle: "Carla Bruni is an associate od Donald John Trump",
  dataSet: ["PEP", "SAN", "PRE", "PEP", "SAN", "PRE", "PEP", "SAN", "PRE"],
};

export const SANCTIONS_DATAS = {
  types: [
    { id: 0, title: "Human Rights" },
    { id: 1, title: "Terrorism" },
  ],
  measures: [
    { id: 0, title: "Asset Freeze" },
    { id: 1, title: "Travel Ban" },
  ],
  events: [
    {
      id: 0,
      title: "Added",
      date: "2021-02-19",
      evidence: [
        {
          id: 0,
          title: "23219889",
          captured: "2021-01-19",
          published: "2021-01-18",
          source: "link",
          datasets: ["DD", "ABC", "ABCD"],
          summary: "summary",
          score: "high credibility Score",
        },
      ],
    },
  ],
};

export const RISKS_DATAS = [
  {
    data: {
      id: 0,
      title: "Financial Crime and Fraud",
      content: "Embezzlement",
      event: [
        {
          id: 0,
          title: "Court Proceedings in Progress : Court Hearing",
          date: "2017",
          evidence: [
            {
              id: 0,
              title: "23219889",
              captured: "2021-01-19",
              source: "link",
              datasets: ["DD", "ABC", "ABCD"],
              summary: "summary",
              score: "high credibility Score",
            },
          ],
        },
      ],
    },
  },
];

export const OTHERS_DATAS = [
  {
    id: 0,
    event: [
      {
        id: 0,
        title: "Court Proceedings in Progress : Court Hearing",
        date: "2017",
        evidence: [
          {
            id: 0,
            title: "23219889",
            captured: "2021-01-19",
            source: "link",
            datasets: ["DD", "ABC", "ABCD"],
            summary: "summary",
            score: "high credibility Score",
          },
        ],
        position: [
          {
            id: 0,
            title: "Former President / US Presidency",
            content:
              "Executive Branch - Head of State and Deputy in United States of America (the)",
            date: "2017-01-20 to 2021-01-20",
          },
        ],
      },
    ],
  },
];

export const OTHERS_MENUS = [
  { id: 0, title: "Profile of Interest (1)" },
  { id: 1, title: "Regulatory Enforcement List (2)" },
  { id: 2, title: "Regulatory Enforcement Lis2t (2)" },
];

export const EVIDENCE_MENUS = [
  { id: 0, title: "ALL (30)" },
  { id: 1, title: "REL (5)" },
  { id: 2, title: "SAN (1)" },
  { id: 3, title: "RRE (18)" },
  { id: 4, title: "PEP (17)" },
  { id: 5, title: "CORP (7)" },
  { id: 6, title: "ID (11)" },
  { id: 7, title: "POI (1)" },
];

export const EVIDENCE_DATAS = [
  {
    id: 0,
    title:
      "23505207 : Attorney General James Sues Donald Trump for Years of Financial Fraud",
    evidence: {
      id: 0,
      captured: "2021-01-19",
      published: "2022-09-21",
      title: "23219889",
      source: "link",
      datasets: ["DD", "ABC", "ABCD"],
      summary: "summary",
      score: "high credibility Score",
    },
  },
];
